# Site settings
title: Blog - technology and science at TheReviewIndex
description: "A blog for sharing thoughts on technology, science and insights at TheReviewIndex."
url: "http://www.qawsed6518.github.io/"
ogimage: "img/default-ogimage.png"
author:
  name: "DH KIM"
  email: "qawsed6518@gmail.com"
  url: "https://www.qawsed6518.github.io"


# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
